name: "GreenCity-Terraform"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Empty-bucket:
    name: Empty S3 Bucket
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
 
      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://romanstripa.ie.guiub8398682jhf0s --recursive

  Plan:
    needs: Empty-bucket
    uses: roman-98/aws-restart-final-project/.github/workflows/aws_tf_plan.yml@main
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: roman-98/aws-restart-final-project/.github/workflows/aws_tf_apply.yml@main
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Deploy:
    needs: Apply
    name: Deploy Website to S3
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync files to S3
        run: |
          aws s3 cp ./index.html s3://romanstripa.ie.guiub8398682jhf0s/

  